# what is numpy?
    Numpy is an short for Numerical python.
    It is python library used for working with ndarrays(multidimensional arrays) and it used for      mathematical operation
    

what is difference between python list and numpy?

        this both looks similar with bracket[]
        python list can contain different data types within single list(like int,float,string).
        but numpy array stores same types of element 

why we use numpy array?

     Numpy array is faster than normal python list
     it uses less memory space to store data

In [1]:
#if you dont have numpy library in ur python ,type download
#pip install numpy

In [2]:
#how to import numpy module from python
import numpy as np
# "as" elias

In [3]:
#creating array list
a=np.array([1,9,5,3,7,8])
#np mean numpy library or module
# . mean object,we call
#array mean collection items in same datatype contigous(next to next) memory locations
display(a)

array([1, 9, 5, 3, 7, 8])

examples

In [4]:
b=np.array([1,2,3,4])#one dimensional array
c=np.array([[1,2,3],[2,3,4],[7,8,9]])# this is two dimensional array
display(c)
display(b)

array([[1, 2, 3],
       [2, 3, 4],
       [7, 8, 9]])

array([1, 2, 3, 4])

# Array indexing
 indexing always starts from "0"
  we can access data using indexing.
  there are two indicing positive indexing starts from 0
  and negative indexing starts from -1


In [5]:
a=np.array([1,2,3,4,5,6])

In [6]:
#example
print(a[0])
print(a[3])


1
4


In [7]:
c=np.array([[1,2,3],[2,3,4],[7,8,9]])
print(c)


[[1 2 3]
 [2 3 4]
 [7 8 9]]


In [8]:
print(c[0,1])

2


In [9]:
c[2,-2]

8

In [10]:
c[-1]

array([7, 8, 9])

In [11]:
#we can also modify values
c[0,0]=6
c

array([[6, 2, 3],
       [2, 3, 4],
       [7, 8, 9]])

In [12]:
c[0]=3.5464 # numpy array have fixed data type,you can change values in normal python list
print(c)

[[3 3 3]
 [2 3 4]
 [7 8 9]]


# Fancy Indexing

  fancy indexing is an passing array of indicies to access the multiple array elements at once
  
  this is allow us to very quickly and modified complicated subset of an array 's values

When using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed:

In [13]:
a=np.array([1,2,3,7,8,9,4,5,8,6])
ind1=[1,2,4]
print(a[ind1])

[2 3 8]


In [14]:
b=np.array([[1,2],[5,8]])
print(a[b])

[[2 3]
 [9 8]]


In [15]:
ind = np.array([[3, 7],
                [4, 5]])
a[ind]

array([[7, 5],
       [8, 9]])

# Array slicing

one dimensional silicing

In [16]:
d=np.array([1,2,3,4,5,6,7,8])
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:

print(d[:4]) #first four elements
print(d[2:]) #after index 2 

[1 2 3 4]
[3 4 5 6 7 8]


In [18]:
d[2:6]#middle subarray

array([3, 4, 5, 6])

x[start:stop:step]

In [19]:
d[::2]

array([1, 3, 5, 7])

In [20]:
d[1::5]

array([2, 7])

In [21]:
d[::-1]#reversed array

array([8, 7, 6, 5, 4, 3, 2, 1])

# Multidimensional array silicing

In [22]:
df=np.array([[1,2,3],[4,5,6],[7,8,9,]])
df

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
df[:2,:3]  #two rows, three columns

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
df[:3,::2]  #all rows,every other columns

array([[1, 3],
       [4, 6],
       [7, 9]])

In [25]:
df[::-1,::-1]  #evry other rows,every other columns

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

--------

# Attributes of an array

In [26]:
df=np.array([8,6,4,3,2,1])
df

array([8, 6, 4, 3, 2, 1])

In [27]:
df1=np.arange(0,10,dtype="float").reshape(2,5)
print(df1)
print('number of dimension:',df1.ndim)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
number of dimension: 2


In [28]:
df.ndim #number of dimension

1

In [29]:
df1.shape #size of each dimension

(2, 5)

In [30]:
df1.size # total number of values

10

In [31]:
df1.dtype

dtype('float64')

In [32]:
df1.itemsize

8

# np.zeros and np.ones

In [38]:
a=np.zeros(3) #one dimensional
a

array([0., 0., 0.])

In [ ]:
arr=np.zeros((3,3)) #creates array of zeros with dimensions defined by the shape of argument
arr

In [ ]:
ar=np.ones((4,4),dtype=int)
ar

In [ ]:
#np.full((3,3),5)

  copy() 
  
  function the  content are physically stored in different location.
  
to complete generate and distinct array .

 original copy does not change

In [ ]:
df=np.array([1,2,3,5,6])
df1=df.copy()
df1

In [ ]:
df1[2]=7
df1

In [ ]:
df

# arange().

it is array creation rountines based on numerical values.
difference between range and arange.

range is an python library.

arange is an third party library.

array range is an arange()

syntax: np.arange(start,stop,step)

In [ ]:
df=np.arange(0,20) #it creates one dimensional array with comma seperated numbers
df

In [ ]:
s=np.arange(2,18,2)
s

In [ ]:
s.shape

In [ ]:
#we can change it also 2 dimensions
s.reshape(2,4)

In [ ]:
s.reshape(8,1)

# linspace()

it is returns numpy array evently spaced number over a specified interval

it seperates your values equal parts

In [ ]:
np.linspace(0,10,20,dtype='int')

In [ ]:
f=np.linspace(0,5,16)
f

------------

# Array manipulation
  
    1.changing array shape
    2.Transpose like operations
    3.joining array
    4.spliting array

# reshape()

In [ ]:
f.reshape(4,4)

In [ ]:
x=np.array([1,4,6,8,3])
x.reshape((5,1))

# np.concatenate()

it is possible to combine multiple array into one single array

Note:
   
   the axis parameters the specifies of the index of the new axis in the dimensions of the results

In [ ]:
x=np.arange(10,20).reshape(2,5)
#print(x)

y=np.arange(40,50).reshape(2,5)
#print(y)

print(np.concatenate([x,y]))

In [ ]:
x=np.array([[1,2],[3,4]])
print('the value of x=\n',x)
y=np.array([[12,23]])
print('\n the value of y=\n',y)
print('\nconcatenate =',np.concatenate((x,y),axis=None))


In [ ]:
np.concatenate((x,y),axis=0)

In [ ]:
np.concatenate((x,y.T),axis=1)

# joining array

stack

vstack 

hstack

column_stack

stacks joins sequence of arrays along a new axis


In [ ]:
a=np.array([1,2,4])
b=np.array([4,5,6])
arr=np.stack((a,b)) #size of the array must be same stack
arr

In [ ]:
#column_stack()-1D array as columns into 
c=np.array([7,8,9])
c

In [ ]:
df1=np.column_stack((a,b,c))
df1

In [ ]:
#hstack
np.hstack((a,b))

In [ ]:
#vstack
np.vstack((a,b))

# spliting array
    split()
    hsplit()
    vsplit()

In [ ]:
#split() - splits an array into multiple sub arrays
x=np.arange(9).reshape((3,3))
print(x)
np.split(x,3)

In [ ]:
np.hsplit(x,3) # horizontally splits array

In [ ]:
arr=np.arange(16).reshape(4,4)
print(arr)

np.vsplit(arr,2) #split array the vertically

# Ravel

ravel()

it is used to two dimensional array convert into one dimensional array 

In [ ]:
arr

In [ ]:
ar1=np.ravel(arr)
ar1

# Transpose
transpose()

this functions is used to invert columns with rows

In [ ]:
a = np.array([[1, 2], [3, 4]])
a.transpose()

----

# Arithmetic operations in numpy

In [ ]:
a=np.arange(2,22)
print('multiplication:',a*3)
print('subtraction:',a-2)
print('addition:',a+2)

In [ ]:
a1=np.arange(6).reshape(2,3)
#print(a1)
a2=np.arange(10,16).reshape(2,3)
#print(a2)
print(a1+a2)
print(a1-a2)
print(a1*a2)


# Matrix product

it is element wise operation
we have performed ,matrix operations a and b

In [ ]:
b1=np.arange(2,10).reshape(2,4)
print('b1 = \n',b1)
b2=np.arange(3,11).reshape(4,2)
print('b2 = \n',b2)
np.dot(b1,b2)   #when you product the two matrix first value shape 2*4 and second 4*2 #4*4 look same

----

# Universal functions.

it is an element wise operations;

Types of universal functions.
           
    1.Math operation 
          add()
          log()
          sqrt()
    2.Trigonometric operation
          sin()
          cos()
          hypot()
    3.Bit Twilding operation
          isinfinite()
          isnan()
    4.comparsion operation 
          greaterthan()
          less()
          equal()
    5.floating operations
          bitwise_and()
          bitwise_or()

# Math operation

In [ ]:
#add()
x1 = np.arange(9.0).reshape((3, 3))
print(x1)
x2 = np.arange(3.0)
print(x2)
np.add(x1, x2)

In [ ]:
#math operation
a=np.array([1,4,9])
b=[4,16,25,36]
print(np.sqrt(a))
print(np.sqrt(b))

In [ ]:
#mod this product of matrix
a=np.arange(2,15)
b=np.mod(a,2) #a divided by "2",remainder is 0,1,0,1
print(b)

In [ ]:
#log()
#it is the inverse of exponential function as well as element wise natural algorithm
#log(exp(x))=x ,it is the reverse of exponential function
#np.log(x,out ,where) , b power of y= a  ###,i.e. by= a ⇔log b a=y

#6 power of 2 = 36 -exponent     Log6 36 = 2 -logarthims
#10 power of 2 = 100             Log10 100 = 2


In [ ]:
y=np.log([1,2,4])
print(y)
z=np.log(2)
print(z)

# floating operation

10 & 7 = 2!

[python-bitwise-and-operator.png](attachment:python-bitwise-and-operator.png)
example

a =10 =>1010 

b = 7 =>0111

10 & 2=>0010 =>decimal number = 2
       
10 | 2=>1111 => decimal number=>15


In [ ]:
print('decimal number',np.bitwise_and(10,7))
print('decimal number',np.bitwise_or(10,7))


# Trigonometric operation
sin(35°)	=  Opposite\Hypotenuse =  2.8\4.9 = 0.57...
 	 
cos(35°)	=  Adjacent\Hypotenuse =  4.0\4.9= 0.82...
 	 
tan(35°)	=  Opposite\Adjacent= 2.8\4.0   = 0.70...


hypotenuse formula = √ ((base2) + (height 2))

=√(52+132)
=√25+169
=√194
=13.98

In [ ]:
base=8
height=12
np.hypot(base,height)

# Bit Twilding operation
isnan() = tests element wise for NaN(not a number) and returns result as a boolean array

In [ ]:
np.log(-1)

In [ ]:
np.log(12)

In [ ]:
x=(np.log(-1),1.,np.log(12))
np.isnan(x)

# comparsion operation

In [ ]:
x = np.array([0, 2, 3, 0, 1, 6, 5, 2])
print('Original Array = ', x)
print('\nGreater Than 0 = \n ', np.greater(x, 0))
print(' \n less Than 1 = \n', np.less(x, 1))
print('\n equal =\n',np.equal(x,2))

 

--------------

# Aggregate Functions

sum of all elements in array

sum :  a.sum()

max  : a.max()

min   : a.min()

mean   :a.mean()

std    :a.std()

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.std()

# Logic Function:

    Testing truth value

    testing array type

    logical operations

     comparsions

np.all() - tests whether any array element along axis evaluate to true

not a number- positivity infinity and negatively infinity evaluate to true because these are not equal to zero

https://www.sharpsightlabs.com/blog/numpy-all/

In [ ]:
np.all([-1,2,3])

In [ ]:
np.all([0,1,2])

In [ ]:
np.iscomplex([2j,2+3j,9]) # true if input element is complex

In [ ]:
np.isreal([2j,3,9j]) #true if input element is real

In [ ]:
#x=[0,1,2,3,4,5,6,7]
# Python program explaining

x = np.arange(6)
np.logical_and(x>1, x<4)


In [ ]:
#np.logical_or()

x = np.arange(7)
print(x)

np.logical_or(x < 2, x > 4)


In [ ]:
#np.logical_not()
x = np.arange(6)

np.logical_not(x < 4)


In [ ]:
#np.greater([[1,2,3,4,5],[3,4,5,6,7]])
# Python Program illustrating
# numpy.greater_equal() method
a = np.array([4,2])
b = np.array([6,2])

print("Is a greater_equal than b : ", a >= b)


In [ ]:
x = np.array([6,4])
y = np.array([2,4])
print(x>y)
print(x<y)
print(x>=y)


for reference

w3source
 
https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html